#!/usr/bin/env python3
"""
Platform CSV exporters for governed delivery ticket packages.

These exporters read the generic ticket JSON generated by governed_delivery_cli.py
and emit import-friendly CSVs for Azure DevOps, Rally, and Asana.

The goal is pragmatic export coverage, not perfect one-click imports for every
customer configuration. Enterprise tools often have customized fields, so these
CSVs intentionally keep governance metadata visible and mappable.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


REQUIRED_GOVERNANCE_FIELDS = [
    "Risk Rating",
    "Timeline Risk Rating",
    "Legal Review Required",
    "Security Review Required",
    "Data Governance Required",
    "QA Required",
    "PHI Flag",
    "PII Flag",
    "External Recipient",
    "File Movement Required",
    "Launch Blocker",
]


def load_tickets(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Ticket JSON not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("generated_ticket_hierarchy.json must contain a list of tickets")
    return data


def yes_no(value: Any) -> str:
    return "Yes" if bool(value) else "No"


def join_list(value: Any, separator: str = " | ") -> str:
    if isinstance(value, list):
        return separator.join(str(item) for item in value)
    if value is None:
        return ""
    return str(value)


def work_item_label(ticket: dict[str, Any]) -> str:
    return str(ticket.get("work_item_type", "task")).replace("_", " ").title()


def governance_fields(ticket: dict[str, Any]) -> dict[str, str]:
    return {
        "Risk Rating": str(ticket.get("risk_rating", "")),
        "Timeline Risk Rating": str(ticket.get("timeline_risk_rating", "")),
        "Legal Review Required": yes_no(ticket.get("legal_review_required")),
        "Security Review Required": yes_no(ticket.get("security_review_required")),
        "Data Governance Required": yes_no(ticket.get("data_governance_required")),
        "QA Required": yes_no(ticket.get("qa_required")),
        "PHI Flag": yes_no(ticket.get("phi_flag")),
        "PII Flag": yes_no(ticket.get("pii_flag")),
        "External Recipient": yes_no(ticket.get("external_recipient")),
        "File Movement Required": yes_no(ticket.get("file_movement_required")),
        "Launch Blocker": yes_no(ticket.get("launch_blocker")),
    }


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_ado_csv(path: Path, tickets: list[dict[str, Any]]) -> None:
    """Write a pragmatic Azure DevOps import CSV."""
    fieldnames = [
        "Work Item Type",
        "Title",
        "Parent External ID",
        "Description",
        "Acceptance Criteria",
        "Definition of Done",
        "Priority",
        "Assigned To",
        "Tags",
        "Owner Role",
        *REQUIRED_GOVERNANCE_FIELDS,
        "Evidence Required",
        "External ID",
    ]

    type_map = {
        "initiative": "Epic",
        "epic": "Feature",
        "feature": "Feature",
        "story": "User Story",
        "task": "Task",
        "subtask": "Task",
        "bug": "Bug",
        "defect": "Bug",
        "approval": "Task",
        "risk": "Issue",
    }

    rows = []
    for ticket in tickets:
        rows.append({
            "Work Item Type": type_map.get(ticket.get("work_item_type", "task"), "Task"),
            "Title": str(ticket.get("title", "")),
            "Parent External ID": str(ticket.get("parent_external_id", "")),
            "Description": str(ticket.get("description", "")),
            "Acceptance Criteria": join_list(ticket.get("acceptance_criteria")),
            "Definition of Done": join_list(ticket.get("definition_of_done")),
            "Priority": str(ticket.get("priority", "")).title(),
            "Assigned To": str(ticket.get("assignee", "TBD")),
            "Tags": "; ".join(filter(None, ["GovernedDelivery", str(ticket.get("program", "")), str(ticket.get("client", "")), "FileMover"])),
            "Owner Role": str(ticket.get("owner_role", "")),
            **governance_fields(ticket),
            "Evidence Required": join_list(ticket.get("evidence_required")),
            "External ID": str(ticket.get("external_id", "")),
        })

    write_csv(path, fieldnames, rows)


def write_rally_csv(path: Path, tickets: list[dict[str, Any]]) -> None:
    """Write a pragmatic Rally import CSV."""
    fieldnames = [
        "Formatted ID",
        "Work Item Type",
        "Name",
        "Parent",
        "Description",
        "Plan Estimate",
        "Schedule State",
        "Priority",
        "Tags",
        "Owner Role",
        *REQUIRED_GOVERNANCE_FIELDS,
        "Acceptance Criteria",
        "Evidence Required",
    ]

    type_map = {
        "initiative": "Portfolio Item: Initiative",
        "epic": "Portfolio Item: Feature",
        "feature": "Portfolio Item: Feature",
        "story": "User Story",
        "task": "Task",
        "subtask": "Task",
        "bug": "Defect",
        "defect": "Defect",
        "approval": "Task",
        "risk": "Risk",
    }

    rows = []
    for ticket in tickets:
        rows.append({
            "Formatted ID": str(ticket.get("external_id", "")),
            "Work Item Type": type_map.get(ticket.get("work_item_type", "task"), "Task"),
            "Name": str(ticket.get("title", "")),
            "Parent": str(ticket.get("parent_external_id", "")),
            "Description": str(ticket.get("description", "")),
            "Plan Estimate": "",
            "Schedule State": "Defined",
            "Priority": str(ticket.get("priority", "")).title(),
            "Tags": " ".join(filter(None, ["GovernedDelivery", str(ticket.get("program", "")), str(ticket.get("client", "")), "FileMover"])),
            "Owner Role": str(ticket.get("owner_role", "")),
            **governance_fields(ticket),
            "Acceptance Criteria": join_list(ticket.get("acceptance_criteria")),
            "Evidence Required": join_list(ticket.get("evidence_required")),
        })

    write_csv(path, fieldnames, rows)


def write_asana_csv(path: Path, tickets: list[dict[str, Any]]) -> None:
    """Write a pragmatic Asana import CSV."""
    fieldnames = [
        "Task ID",
        "Parent Task ID",
        "Task Name",
        "Section/Column",
        "Description",
        "Assignee",
        "Due Date",
        "Priority",
        "Tags",
        "Owner Role",
        *REQUIRED_GOVERNANCE_FIELDS,
        "Acceptance Criteria",
        "Evidence Required",
    ]

    rows = []
    for ticket in tickets:
        section = {
            "initiative": "Initiatives",
            "epic": "Epics",
            "feature": "Features",
            "story": "Stories",
            "task": "Tasks",
            "subtask": "Subtasks",
            "bug": "Defects",
            "defect": "Defects",
            "approval": "Approvals",
            "risk": "Risks",
        }.get(ticket.get("work_item_type", "task"), "Tasks")

        rows.append({
            "Task ID": str(ticket.get("external_id", "")),
            "Parent Task ID": str(ticket.get("parent_external_id", "")),
            "Task Name": str(ticket.get("title", "")),
            "Section/Column": section,
            "Description": str(ticket.get("description", "")),
            "Assignee": str(ticket.get("assignee", "TBD")),
            "Due Date": str(ticket.get("due_date", "")),
            "Priority": str(ticket.get("priority", "")).title(),
            "Tags": ",".join(filter(None, ["GovernedDelivery", str(ticket.get("program", "")), str(ticket.get("client", "")), "FileMover"])),
            "Owner Role": str(ticket.get("owner_role", "")),
            **governance_fields(ticket),
            "Acceptance Criteria": join_list(ticket.get("acceptance_criteria")),
            "Evidence Required": join_list(ticket.get("evidence_required")),
        })

    write_csv(path, fieldnames, rows)


def write_all_platform_exports(output_dir: Path) -> list[Path]:
    ticket_path = output_dir / "generated_ticket_hierarchy.json"
    tickets = load_tickets(ticket_path)
    outputs = [
        output_dir / "ado_export.csv",
        output_dir / "rally_export.csv",
        output_dir / "asana_export.csv",
    ]
    write_ado_csv(outputs[0], tickets)
    write_rally_csv(outputs[1], tickets)
    write_asana_csv(outputs[2], tickets)
    return outputs
